version: '3.8'

services:
  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "3004:3004"
    environment:
      - MONGOURI=mongodb://mongo:27017/urlshortener
      - BASEURL=http://54.153.178.15
    depends_on:
      - mongo
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: url-shortener-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  nginx:
    image: nginx:alpine
    container_name: url-shortener-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: always  

volumes:
  mongo-data: